parser: remove unused function
Fixes:
llvm2c/parser/createExpressions.cpp:60:61: error: unused function 'args_wrapper' [-Werror,-Wunused-function]
static inline llvm::iterator_range<llvm::User::op_iterator> args_wrapper(llvm::CallInst *CI) {